// Code Generated by Sidekick is for learning and experimentation purposes only.
package org.example

class LambdaDeployer implements Serializable {
    def steps

    LambdaDeployer(steps) {
        this.steps = steps
    }

    /**
     * Deploys code to an AWS Lambda function.
     * Usage params: functionName, s3Bucket, s3Key, awsRegion, awsCredentialsId
     */
    def deploy(Map config) {
        steps.withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: config.awsCredentialsId
        ]]) {
            steps.sh """
                export AWS_DEFAULT_REGION='${config.awsRegion}'
                aws lambda update-function-code \\
                  --function-name '${config.functionName}' \\
                  --s3-bucket '${config.s3Bucket}' \\
                  --s3-key '${config.s3Key}'
            """
        }
        steps.echo "Deployment to Lambda function '${config.functionName}' in region '${config.awsRegion}' initiated."
    }
}
